<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-R4JMQ25" failures="1" tests="3" name="Test" time="73.371" errors="0" timestamp="2025-01-05T12:15:16 IST">
  <testcase classname="com.opencart.TestLayer.AddressTest" name="verifyAddressDeleteSuccessfully" time="3.382"/>
  <testcase classname="com.opencart.TestLayer.AddressTest" name="verifyAddressEditSuccessfully" time="5.092"/>
  <testcase classname="com.opencart.TestLayer.AddressTest" name="verifyAddressSaveSuccessfully" time="8.458">
    <failure type="java.lang.AssertionError" message="expected [Your address has been successfully adde] but found [Your address has been successfully added]">
      <![CDATA[java.lang.AssertionError: expected [Your address has been successfully adde] but found [Your address has been successfully added]
at com.opencart.TestLayer.AddressTest.verifyAddressSaveSuccessfully(AddressTest.java:48)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddressSaveSuccessfully -->
</testsuite> <!-- Test -->
